  model:
    name: multihead_model_tower

    fusion:
      hidden_dims: [1024, 512, 256]
      dropout: 0.1
      
    heads: # targets resolved from heads
        subcategory:
          type: classification
          tower_dims: [128]
          dropout: 0.1
          out_dim: 14        # number of subcategory classes
          class_weights: [1.06415277e-02, 4.73492474e-04, 1.13053865e-03, 1.29481508e-01,
            3.35022083e-02, 2.71588197e-02, 1.69262853e-02, 7.96769523e-03,
            2.14334994e-02, 5.84245828e-01, 6.59165629e-02, 3.17188545e-02,
            4.11017140e-04, 6.89921629e-02]
          loss_weight: 3
        priority:
          type: binary
          out_dim: 1      # number of priority classes
          class_weights: [0.8920187, 0.1079813]
        avariya:
          type: binary
          out_dim: 1
          class_weights: [0.0158328, 0.9841672]

  features:
    oe_cats:
      path: oe_cat_features.npz
      cardinalities: [23, 881, 6] # S_NAME, REG, SOURCE
      emb_dim: 16
    bin_cats:
      path: bin_cat_features.npz
      input_dim: 17 # 16 sensitive + HAS_TEXT
    times:
      path: time_features.npz
      mlp_dims: [32, 16]
      input_dim: 7
    text:
      path: question_bge_m3.npz
      mlp_dims: [512, 256]
      input_dim: 1024

  training:
    batch_size: 32
    epochs: 30
    lr: 0.0005
    num_workers: 10

  # logging:
  #   level: INFO
