model:
  name: multihead_model_tower
  path: C:\Users\mew\Projects\autotickets-rag-bot\runs\dl\2025-08-27_14-38-14_multihead_model_tower\intermediate_checkpoint.pt
  cfg_path: C:\Users\mew\Projects\autotickets-rag-bot\runs\dl\2025-08-27_14-38-14_multihead_model_tower\resolved_config.yaml

# Preprocessing / feature engeneering
preprocessing:
  text_cols: [QUESTION]
  emb_text_col: QUESTION_clean

  categorical: [S_NAME, REG, SOURCE]
  time: [OPEN_TIME_]
  embedding_model_path: "./models/embeddings/deepvk_USER-bge-m3"
  
  cat_encoders:
    S_NAME: "./models/vectorizers/S_NAME_oenc.pkl"
    REG: "./models/vectorizers/REG_oenc.pkl"
    SOURCE: "./models/vectorizers/SOURCE_oenc.pkl"

  SENSITIVE_PATTERNS:
    EMAIL: "\\b[A-Za-z0-9._%+-]+@(?:[A-Za-z0-9-]+\\.)+[A-Za-z]{2,}\\b"
    PHONE: "\\b(?:\\+7|8)?[\\s-]?\\(?\\d{3,4}\\)?[\\s-]?\\d{2,3}[\\s-]?\\d{2}[\\s-]?\\d{2}\\b"
    INN: "(?i)инн\\s*\\d{5,12}"
    VIN: "\\b[A-HJ-NPR-Z0-9]{17}\\b"
    INCEDENT: "\\bIM\\d{8,12}\\b"
    REG_NUMBER: "\\b[АВЕКМНОРСТУХ]{1,3}\\d{3,4}[АВЕКМНОРСТУХ]{2}\\b"
    CASE_NO: "\\b(?:[CcSs]D|T)\\d{6,10}\\b"
    APPEAL_NO: "\\b\\d/\\d{9,12}\\b"
    DOC_NO: "№\\s?\\d{1,6}([/\\-]?\\d{1,6})?([А-ЯA-Z])?"
    LONG_ID: "\\b\\d{9,}\\b|\\b[a-f0-9]{32,128}\\b|(?:UID|GlndID|GUID)[: ]?[0-9a-fA-F\\-]{16,128}"
    IP: "\\b(?:\\d{1,3}\\.){3}\\d{1,3}\\b"
    DATE: "\\b\\d{2}[./-]\\d{2}[./-]\\d{2,4}(?:\\s?г\\.?)*"
    FIO: "\\b[А-ЯЁ][а-яё]+ [А-ЯЁ]\\.[А-ЯЁ]\\.(?=[\\s,.)/]|$)"
    USERNAME: "\\b[a-zA-Z][a-zA-Z0-9]{3,15}\\d\\b"
    TOKEN: "\\b[a-f0-9]{16,64}\\b|\\b(?=.*[A-Z])(?=.*[a-z])(?=.*\\d)[A-Za-z0-9]{12,64}\\b"
    URL: "https?://[^\\s]+"

  TEXT_PLACEHOLDER: "[NO_TEXT]"

  EMPTY_QUESTION_PATTERNS:
    - "\\bnan\\b"
    - "\\bNan\\b"
    - "\\bNone\\b"
    - "\\bNull\\b"
    - "\\bпусто\\b"
    - "отсутствует текст описание пустое"
    - "fwd:\\s*описание пустое"
    - "пустое описание"
    - "описание пустое"
    - "отсутствует текст"
    - "\\bотсутствует\\b"
    - "\\bнету\\b"
    - "\\bнет\\b"

  SERVICE_KILL_MARKERS:
    - "The mail"
    - "Уведомляющий Сервер"
    - "Postfix Queue ID"
    - "Postfix Sender"
    - "Arrival Date"
    - "Recipient:"
    - "Original Recipient:"
    - "Diagnostic Code"
    - "in reply to RCPT TO command"
    - "Mail received:"
    - "Message ID:"
    - "Mail server"
    - "Receive Notification Mail"
    - "Pronto! HTML5 Feedback Pronto! HTML5 client version"

  SERVICE_LEFT_MARKERS:
    - "pronto! html5 feedback"
    - "Fwd:"
    - "Fwd: Re:"
    - "Fwd: Fwd:"

postprocessing:
  heads:
    subcategory:
      type: classification
      mapping_path: "C:/Users/mew/Projects/autotickets-rag-bot/models/vectorizers/SUBCATEGORY_clean_lenc.pkl"
    priority:
      type: binary
      mapping: {0: "2", 1: "3"}  # optional
      threshold: 0.5
    avariya:
      type: binary
      mapping: {0: "Нет", 1: "Да"}   # optional
      threshold: 0.5

UI_TO_DS_COL: 
  region: "REG"
  source: "SOURCE"
  service: "S_NAME"
  question: "QUESTION"

  
# ------------------------
# Optional: inference / deployment settings
# ------------------------
inference:
  # device: "cpu"     # or "cuda"
  batch_size: 1
