seed: 42

target: avariya
features:
  - cat_features.npz
  - time_features.npz
  - question_bge_m3.npz

validation:
  n_splits: 5 
  stratify_by: avariya

model:
  name: catboost
  params:
    loss_function: LogLoss
    eval_metric: F1
    learning_rate: 0.1
    depth: 7
    l2_leaf_reg: 3.0
    iterations: 10000
    verbose: 10
    thread_count: -1
    border_count: 128
    early_stopping_rounds: 100

search_space:
  iterations:
    type: int
    low: 1000
    high: 2500
  depth:
    type: int
    low: 5
    high: 8
  # learning_rate:
  #   type: float
  #   low: 0.01
  #   high: 0.3
  #   log: true
  # l2_leaf_reg:
  #   type: float
  #   low: 0.01
  #   high: 10.0
  #   log: true
  # border_count:
  #   type: int
  #   low: 32
  #   high: 255

class_weight: balanced
max_samples: 10000
