seed: 42

target: subcategory
features:
  - cat_features.npz
  - time_features.npz
  # - question_tfidf.npz
  - question_bge_m3.npz

validation:
  n_splits: 5 
  stratify_by: subcategory

model:
  name: catboost
  params:
    loss_function: MultiClass
    eval_metric: TotalF1
    learning_rate: 0.05
    depth: 6
    l2_leaf_reg: 3.0
    random_seed: 42
    iterations: 500
    verbose: 10
    thread_count: -1
    border_count: 128
    early_stopping_rounds: 30
    class_weights: balanced

search_space:
  iterations:
    type: int
    low: 90
    high: 400
  depth:
    type: int
    low: 5
    high: 7
  # learning_rate:
  #   type: float
  #   low: 0.01
  #   high: 0.3
  #   log: true
  l2_leaf_reg:
    type: float
    low: 0.01
    high: 10.0
    log: true
  # border_count:
  #   type: int
  #   low: 32
  #   high: 255

class_weight: balanced
max_samples: 40000
